# Command Line
These are my notes from the excellent tutorial: <a href='https://www.learnenough.com/command-line-tutorial#fig-tech_support_cheat_sheet'>Learn Enough Command Line to Be Dangerous</a>!

## Shortcuts 
ShortCuts | Definitions
------------ | ----------------------------------------
new tab | cmd+t
close tab | cmd+w
^A | go the beginning of the command 
^E | go to the end of the line 
^U | clear line 
hold ⌥ + click | move to specified spot in line 
^L | clear previous text
^R | search interactively and edit previous commands

## Commands 
Command | Definition
------- | ----------------------------------------------------------------------
echo | print strings to screen
mkdir | create directory 
cd | change directory 
pwd | print working directory 
crtl+c | best for “getting out of trouble” (cancel as a mnemonic) 
q | quits out of text editor windows / man windows 
clear| removes all previous text 
sleep x | puts the terminal to sleep for “x” seconds, processes commands typed during sleep mode afterwards
`>` (redirect operator) | use cat + fileName to write contents of a file to a new file | writes output to a file
`>>` (append operator) | writes output to the end of a file 
curl| download a file from a URL `curl -OL cdn.learnenough.com/sonnets.txt`
!! (bang)| re-run previous command 
!curl | (re-run previous curl command)
history | show previous command history 
<br>
<br>

File related Command | Definition
------- | ----------------------------------------------------------------------
open | opens the argument using the default application 
cat | dumps contents onto the screen, can accept multiple args
diff | shows differences between two files 
ls | list all files and directories (supports some regex expressions)
ls -l | lists files in long format with date modified and size 
ls -rtl | lists files in reverse order of modification 
ls -a | show hidden files 
ls -h | adds human readable byte count
mv (move)| rename a file or directory 
cp | copy a file
rm | remove a file 
head/tail| show first/last 10 lines of a file
wc | shows lines, words, and bytes in a file
rm -rf | delete a directory and all contents recursively 

## Piping
Piping exists in command line!   

+ `head sonnets.txt | wc` - get head of sonnets.txt then pipe result to wc
+ `history | less` - pipe history to less for interactive searching 
    + example: `open -a '/Applications/Microsoft Excel.app' 'Downloads/Utqiagvik_daily_species_counts.csv'`

## Less 
Lets you interactly navigate a file or output.   
Command	| Description	
------- | -----------
up & down arrow keys |	Move up or down one line	
spacebar |	Move forward one page	
⌃F |	Move forward one page	
⌃B |	Move back one page	
G	| Move to end of file	
1G |	Move to beginning of file	
/<string> |	Search file for string	/rose
n	| Move to next search result
N	| Move to previous search result
q	| Quit less

## Man
man + a command opens the documenation for a command 


## Grep (globally search a regular expression and print)
grep is used for simple patterns and basic regular expressions (BREs); egrep can
handle extended regular expressions (EREs).  See re_format(7) for more informa-
tion on regular expressions.  fgrep is quicker than both grep and egrep, but can
only handle fixed patterns (i.e. it does not interpret regular expressions).
Patterns may consist of one or more lines, allowing any of the pattern lines to
match a portion of the input.

zgrep, zegrep, and zfgrep act like grep, egrep, and fgrep, respectively, but
accept input files compressed with the compress(1) or gzip(1) compression utili-
ties.

*Note:* It doesn't work that well (for instance I tried using anchors `^` and `$` with no success).  Better to use a text editor or another language.


## Miscellaneous 
  
+ Unix refers to a family of operating systems that includes Linux, Android, iOS (iPhone/iPad), and macOS
    + the main exception to the unix family is windows
+ touch foo is commonly used to create an empty file 
+ Use `tail -f foo` to view a file that's actively changing 
    + Ex. `ping learneough.com > learneough.log` in one tab and `tail -f learneough.log` in another tab 
+ `/` is the root directory 
+ `cd` by itself defaults to the home directory 
+ `cd ..` goes up one directory 
+ `open .` opens the current directory in default viewer (finder)
+ `cd -` goes to the previous directory, whatever it was
+ you can separate commands in one line using `;`
+ you can chain commands using `&&` that run only if the previous call was successful
+ `grep -ri folder_name` search recursivley through folder 

## Useful commands I've used

### Move downloaded files to another folder 
This command uses `ls -rtl` to list the contents of a folder in reverse download order.  I then pipe the results using `grep` to find the pattern that I want.  I then select the last 4 using `tail -4` since they are in chronological order from top-bottom.  

### recursively find a file 
This command recursively searches through all subdirectories of the second argument for the file witht name "foo".
```
find . -name "foo*"
```

### zip a folder without including folder paths 
The option `-j` refers to junk file paths.  This will zip up the contents of a folder but remove the directory strucutre.  I used this in R when I had to automate creating zip archives.  The initial zip archives I created included the following folder structure: `/home/visitor/McPherson/ADC_Bathymetric_Data_Corrected/NAD83/Garmin/E4_Lake_GIS_Files/E4_Area/E4_Area_20060620.shx` when all I need was for them to be zipped up in an `E4_Area` folder. 

### get file MIME Type
[More information](https://stackoverflow.com/questions/29017725/how-do-you-change-the-mime-type-of-a-file-from-the-terminal). MIME type comes from lots of different places depending on OS and web browswer. In Mac OS, mime type is actually set on downloaded files.  We can access it using the following terminal command:

```
file --mime-type -b science_metadata.xml
```

