# Miscellaneous 

## Basic Principles of Responsive Web Design 
My notes from [9 Basic Principles of Responsive Web Design](http://blog.froont.com/9-basic-principles-of-responsive-web-design/)

+ Responsive and adaptive are not the same thing
+ flow: as screen size becomes smaller, content takes up more vertical space and anything below it is pushed down - this is called `flow`.
+ use relative units - % instead of px
+ breakpoints - allow the layout to change at predefined points
+ use min and max values. A value of `width: 100%` on your phone could make sense but not on your tv.  In that case we could also set a `max-width: 1000px` for that use case. 
+ containers / nesting - wrap elements in containers so that the container can change shape / move, not each element which can get hard to control quickly.
+ webfonts look great but increase loading time, system fonts are much faster. 
+ Image scaling - if an image is going to scale watch out for pixelation - it might be better to use a vector (svg / icon font) to allow it to scale.

## Emojis in HTML
Emojis look like images but they're actually bucketed into the text category.  They're just characters, you can select, copy-paste, adjust their size, and they have a primitive numerical representation. 
  
+ To use them we can either use them directly or specify their unicode representation.
+[Emojipedia](https://emojipedia.org/) is the best to go for copy-pasting emojis.
+In the `<head>` tag be sure to specify the charset as UTF-8 `<meta charset='UTF-8'>`.
+ HTML Codepoint: alternate way to represent an emoji 
    + `&#xCodepoint` 
    + for pizza the codepoint is: `&#x1F355`
    + tells the browswer it's a unicode character
    + F355 is its ID
+ CSS Codepoint: the format is `"\01F355"` for pizza.
+ Javascript: we use the `String.fromCodePoint()` method to specify a unciode representation. 
    + we can also specify it directly as a string. 
+ Character Viewer - we can use the character viewer to see a full list of unicode characters available to us. To open it on mac the command is `crtl + command + space`
+ All characters are actually represented like this.  A is represented as `U+0041`. 
    
Example: 

```
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <title>Mouse move text shadow</title>
    <link rel='stylesheet'>
</head>
<body>
    <div class='container'>
        <h1 id='emoji'>:P</h1>
    </div>
<script>
    let emoji = document.querySelector('#emoji');
    emoji.innerText = String.fromCodePoint(0x1F355);
    emoji.innerText += '😛';
</script>
</body>
</html>
```

### Parentheses in regex 
When using parentheses in regex they can denote a pattern we want to extract, then keep looking for more matches.  For instance in this function we pass in an `element.style.background` property in rgb format and extract the red, blue, and green components.  From there the function adds an offset to them. Something important to note is that the `.match` string method returns all characters that it matched up to and including the parentheses as `match[0]`.

```
function rgbColorOffset(rgbString, offset) {
    const matches = rgbString.match(/^rgb\((\d+),\s(\d+),\s(\d+)/);
    const colors = [matches[1], matches[2], matches[3]];
    return `rgb(${colors.map(color => (parseInt(color) - 255) * -1).join(',')})`;
}
```

### innerText vs textContent 
`innerText` was non-standard, while `textContent` was standardized earlier.
`innerText` returns the visible text contained in a node, while `textContent` returns the full text. For example, on the following HTML <span>Hello <span style="display: none;">World</span></span>, innerText will return 'Hello', while textContent will return 'Hello World'. For a more complete list of differences, see the table at http://perfectionkills.com/the-poor-misunderstood-innerText/.
As a result, innerText is much more performance-heavy: it requires layout information to return the result. https://kellegous.com/j/2013/02/27/innertext-vs-textcontent/

+ `innerText` is not present in firefox
+ Opera, merely computes textContent when you try to access innerText


### Advice for JR devs

+ write small, bite-sized divs.  Each commit should handle one thing
+ overengineered code.  Long functions, random helpers, too many if statements (write a design doc to organize)
+ APM - actions per minute, spend more of your time developing vs. reddit
+ don't have pride / ego - be open to suggestions / criticism 


## Chai.js

Automated tests: 

+ Unit tests: A single piece of code (usually an object or a function) is tested, isolated from other pieces
+ Integration tests: Multiple pieces are tested together, for example testing database access code against a test database
+ Acceptance tests (also called Functional tests): Automatic testing of the entire application, for example using a tool like Selenium to automatically run a browser.

Test Driven Development
TDD or Test-Driven Development is a process for when you write and run your tests. Following it makes it possible to have a very high test-coverage. Test-coverage refers to the percentage of your code that is tested automatically, so a higher number is better. TDD also reduces the likelihood of having bugs in your tests, which can otherwise be difficult to track down.

+ Start by writing a test
+ Run the test and any other tests. At this point, your newly added test should fail. If it doesn’t fail here, it might not be testing the right thing and thus has a bug in it.
+ Write the minimum amount of code required to make the test pass
+ Run the tests to check the new test passes
+ Optionally refactor your code
+ Repeat from 1

BDD - Behavior Driven Development 
BDD states that you test behavior - not implemantation.

This examples tests `implementation` because we're assuming that `counter.count` starts at 0.  However this could change based on our needs.
```
suite('Counter', function() {
  test('tick increases count to 1', function() {
    var counter = new Counter();
 
    counter.tick();
 
    assert.equal(counter.count, 1);
  });
});
```

This example tests `behavior` because we do not assume that `counter.count` starts anywhere.  Instead we test that `counter.count` has been incremented by one after calling `counter.tick()` - thus it could have been initialized to any starting value and the test would pass. 

```
describe('Counter', function() {
  it('should increase count by 1 after calling tick', function() {
    var counter = new Counter();
    var expectedCount = counter.count + 1;
 
    counter.tick();
 
    assert.equal(counter.count, expectedCount);
  });
});
```