# Backbone

## Introduction
In a finished Backbone app, you don't have to write the glue code that looks into the DOM to find an element with a specific id, and update the HTML manually — when the model changes, the views simply update themselves.
  
Model
  
+ Orchestrates data and business logic.
+ Loads and saves data from the server.
+ Emits events when data changes.

View
  
+ Listens for changes and renders UI.
+ Handles user input and interactivity.
+ Sends captured input to the model.

A Model manages an internal table of data attributes, and triggers "change" events when any of its data is modified. Models handle syncing data with a persistence layer — usually a REST API with a backing database. Design your models as the atomic reusable objects containing all of the helpful functions for manipulating their particular bit of data. Models should be able to be passed around throughout your app, and used anywhere that bit of data is needed.

A View is an atomic chunk of user interface. It often renders the data from a specific model, or number of models — but views can also be data-less chunks of UI that stand alone. Models should be generally unaware of views. Instead, views listen to the model "change" events, and react or re-render themselves appropriately.

### Backbone logic 
From the client side the `Router` makes an HTTP request.  For instance (https://test.arcticdata.io/view/urn:uuid:375de5f7-d5cc-483e-b23b-a5199df73111) is an HTTP request.  From there it accesses `Views` and locates what it needs to render based on the request. When a view `event` is fired it will update the `Model`s based on the event which in turn updates the data source.  Then when the Models are updated they in turn update how the `Views` are rendered. 

## Views
The following syntax creates a backbone View using the `.extend` method. Then we create a new instance of the `AppView` view and call it newView.  The `initialize` property is run automatically on creation of a new object. 

```
  var AppView = Backbone.View.extend({
          initialize: function() {
              this.renderView();
              console.log('intialize runs by itself');
          },
          renderView: function() {
              console.log('Hello World');
          }
      });
      const newView = new AppView();
      //newView.renderView();
```


Views create an empty div as a DOM element by default. We need to select a DOM element to pass to a view.

### this.$el
`this.$el` creates a `div` element. If we don't specifiy which div we want to replace in the `el` property then it just logs an empty div 

```
      var FirstView = Backbone.View.extend({
          initialize: function() {
              this.render();
          },
          render: function() {
              this.$el.html('hello from the other side');
              console.log(this.$el);
          }
      });
      var fView = new FirstView({
          //el: '#content'
      });
```

### tagName, className, and Id
When creating a view we can specify the `tagName` (type of DOM element), the `className` (CSS class), and an id. It seems like this only works if we do not specify `el` when creating a new View.  This is why `//el: '#content';` is commented out.

```
    // Setting a tagName, className, and id
      const SecondView = Backbone.View.extend({
          tagName: 'a', // this will create an anchor element
          className: 'some-class',
          id: 'some-id',
          initialize: function() {
              this.render();
          },
          render: function() {
              this.$el.html('second view message');
              console.log(this.$el);
          }
      });
      const SView = new SecondView({
          //el: '#content';
      });
```

### el vs $el
By default backbone sets `this.el` to an empty div (a DOM element) and `this.$el` is a jQuery object that points to it. If we set a `tagName` then it will update the it to the provided element.


## Models
The following example shows using the Model constructor.  We create two instances of the shop model and use the `get` and `set` methods on its attributes.  You can also access them manually by `shopName.attributes.attributeName`.

+ `persistence` - models in real-world applications require persistence that allows us to edit and updat them such that their recent states will be saved somewhere. Example: localStorage or synchronized with a database
+ a model can have multiple views observing it for changes. 
+ It's useful for listen for changes on `Collection`s rather than `Model`s so that we don't have to re-write individual logic per model. This is similar to adding an event listener on a parent div.


```
      // Models
      // Create the Shop constructor? 
      const Shop = Backbone.Model.extend({
          defaults: {
              brand: '',
              type: '',
              price: 0,
              stock: 0
          }
      });
      
      // Create two Shop Model instances 
      const firstShop = new Shop({
          brand: 'Wilson',
          type: 'Basketball',
          price: 60,
          stock: 10
      });
      const secondShop = new Shop({
          brand: 'TF-1000',
          type: 'basketball'
      });
      secondShop.attributes.price = 59.99;
      secondShop.attributes.stock = 12;
      
      // Use get and set methods 
      secondShop.get('brand');
      secondShop.set('price', 100);
      console.log(secondShop.get('price'));
```

## Collections 
Collections are ordered sets of models. You can bind some events to be notified when any model in the collection has been modified. Events such as change, add, remove.

```
      // Create a Collection of Shops 
      const ShopCollection = Backbone.Collection.extend({
          model: Shop
      });
      const shopCollection = new ShopCollection;
      shopCollection.add(firstShop);
      shopCollection.add(secondShop);
      console.log(shopCollection);
      console.log(shopCollection.models);
      
      // Underscore each method to iterate over models
      shopCollection.each((shop) => {
          console.log(shop.get('brand'));
          console.log(shop.get('price'));
      });
```

## Views 2
The views handle user input and interactivity, renders data from the model and also sends captureed input back to the model. The views listen to the model "change" events, and react or re-render themselves appropriately.

## Notes from Backbone-fundamentals 

+ Backbone is a MV* framework.  It has models and views but the distinct controller functionality is baked into the Views / other components. 
+ SPA - web applications that load into the browser and then react to data changes on the client side without requiring complete page refreshes from the server
    + the goals of SPAs is to improve latency (the time before a page something loads after reciving a request).  After the initial page loads they're able to run faster as subsequent navigations and requests for data don't require new page loads. 
+ spaghetti code - unstructured and difficult-to-maintain source code
+ XHR (XMLHttpRequest), typically communicating with a server-side REST API or endpoint
    + Ajax (Asynchronous JavaScript and XML) makes communication with the server asynchronous so that data is transferred and processed in the background, allowing the user to interact with other parts of a page without interruption. This improves usability and responsiveness.

### When to choose MV*
If you’re writing an application where much of the heavy lifting for view rendering and data manipulation will be occurring in the browser, you may find a JavaScript MV* framework useful. Examples of applications that fall into this category are GMail, NewsBlur and the LinkedIn mobile app.

These types of applications typically download a single payload containing all the scripts, stylesheets, and markup users need for common tasks and then perform a lot of additional behavior in the background. For instance, it’s trivial to switch between reading an email or document to writing one without sending a new page request to the server.

If, however, you’re building an application that still relies on the server for most of the heavy-lifting of page/view rendering and you’re just using a little JavaScript or jQuery to make things more interactive, an MV* framework may be overkill. There certainly are complex Web applications where the partial rendering of views can be coupled with a single-page application effectively, but for everything else, you may find yourself better sticking to a simpler setup.

I think this relates to metacatUI b/c you're constantly moving around - switching from package to package and search to search - ask Chris about this 


### MVC with the web 
The web heavily relies on the HTTP protocol, which is stateless. This means that there is not a constantly open connection between the browser and server; each request instantiates a new communication channel between the two. Once the request initiator (e.g. a browser) gets a response the connection is closed. This fact creates a completely different context when compared to one of the operating systems on which many of the original MVC ideas were developed. The MVC implementation has to conform to the web context.

### Front Controller Example 
The way I understand this is that the controller handles everything. It branches off actions based off the request (usually HTTP).

**The Server receives an HTTP request and routes it through a single entry point. At that entry point, the Front Controller analyzes the request and, based on it, invokes an Action of the appropriate Controller. This process is called routing. The Action Model is asked to return and/or save submitted data. The Model communicates with the data source (e.g., database or API). Once the Model completes its work it returns data to the Controller which then loads the appropriate View. The View executes presentation logic (loops through articles and prints titles, content, etc.) using the supplied data. In the end, an HTTP response is returned to the browser.**

For example, let’s say we have our blog on www.example.com and we want to edit an article (with  id=43) and request http://www.example.com/article/edit/43:

On the server side, the Front Controller would analyze the URL and invoke the Article Controller (corresponding to the /article/ part of the URI) and its Edit Action (corresponding to the /edit/ part of the URI). Within the Action there would be a call to, let’s say, the Articles Model and its Articles::getEntry(43) method (43 corresponding to the /43 at the end of the URI). This would return the blog article data from the database for editing. The Article Controller would then load the (article/edit) View which would include logic for injecting the article’s data into a form suitable for editing its content, title, and other (meta) data. Finally, the resulting HTML response would be returned to the browser.

As you can imagine, a similar flow is necessary with POST requests after we press a save button in a form. The POST action URI would look like /article/save/43. The request would go through the same Controller, but this time the Save Action would be invoked (due to the  /save/ URI chunk), the Articles Model would save the edited article to the database with  Articles::saveEntry(43), and the browser would be redirected to the /article/edit/43 URI for further editing.

Finally, if the user requested http://www.example.com/ the Front Controller would invoke the default Controller and Action; e.g., the Index Controller and its Index action. Within Index Action there would be a call to the Articles model and its Articles::getLastEntries(10) method which would return the last 10 blog posts. The Controller would load the blog/index View which would have basic logic for listing the blog posts.


### ToDo View Example 

```
var TodoView = Backbone.View.extend({

  tagName:  'li',

  // Cache the template function for a single item.
  todoTpl: _.template( $('#item-template').html() ),

  events: {
    'dblclick label': 'edit',
    'keypress .edit': 'updateOnEnter',
    'blur .edit':   'close'
  },

  // Called when the view is first created
  initialize: function() {
    this.$el = $('#todo');
    // Later we'll look at:
    // this.listenTo(someCollection, 'all', this.render);
    // but you can actually run this example right now by
    // calling todoView.render();
  },

  // Re-render the titles of the todo item.
  render: function() {
    this.$el.html( this.todoTpl( this.model.attributes ) );
    // $el here is a reference to the jQuery element
    // associated with the view, todoTpl is a reference
    // to an Underscore template and model.attributes
    // contains the attributes of the model.
    // Altogether, the statement is replacing the HTML of
    // a DOM element with the result of instantiating a
    // template with the model's attributes.
    this.input = this.$('.edit');
    return this;
  },

  edit: function() {
    // executed when todo label is double clicked
  },

  close: function() {
    // executed when todo loses focus
  },

  updateOnEnter: function( e ) {
    // executed on each keypress when in todo edit mode,
    // but we'll wait for enter to get in action
  }
});

// create a view for a todo
var todoView = new TodoView({model: myTodo});
```

Notes for this view: 

+ the `events` attribute fulfills the role of the Controller configuration.  It defines the action (callback function) that occurs for each event specified. 
+ Users interact with views - which usually means reading and editing Model data 
+ We define a render() utility within our View which is responsible for rendering the contents of the Model using a JavaScript templating engine (provided by Underscore.js) and updating the contents of our View, referenced by this.$el
+ We then add our `render()` callback as a Model subscriber, so the View can be triggered to update when the Model changes


## Templating 
It has long been considered bad practice (and computationally expensive) to manually create large blocks of HTML markup in-memory through string concatenation. Templating libraries are often used to define templates for Views as HTML markup. Variables are delimited using a variable syntax (e.g `<%= title %>` for Underscore and `{{title}}` for Handlebars).


### initialize and defaults
We can set `default` attributes and an initialize function when defining a model.
```
var myTodo = Backbone.Model.extend({
    initialize: function() {
      console.log('myTodo model initialized');
    },
    // default attribuet values 
    defaults: {
        title: '',
        completed: false,
        name: 'Dom'
    }
});
```

### .toJSON()
If you need to read or clone all of a model’s data attributes, use its toJSON() method. This method returns a copy of the attributes as an object (not a JSON string despite its name). (When JSON.stringify() is passed an object with a toJSON() method, it stringifies the return value of toJSON() instead of the original object. The examples in the previous section took advantage of this feature when they called JSON.stringify() to log model instances.)

```
    var myTodoList = new myTodo(); 
    console.log(myTodoList.toJSON());
    console.log(JSON.stringify(myTodoList));
    // these output of the second call is the stringified version of the first call 
```

### Model.set()
Model.set() sets a hash containing one or more attributes on the model. When any of these attributes alter the state of the model, a “change” event is triggered on it. Change events for each attribute are also triggered and can be bound to (e.g. change:name, change:age).  We can also pass `{silent: true}` to `.set()` in order to remove the event. 

```
    // Set one attribute at a time 
    myTodoList.set('title', 'shopping list');
    // Set both attributes at once
    myTodoList.set({
        title: 'shopping list updated',
        completed: true
    });
```

### Events and Direct Access 
We can create attribute-specific event handlers by referencing `event:hash` in callback function declarations.  These are triggered when the attributes are changed or whatever other event occurs on them.  However if you update them directly through the exposed `.attributes` property, then these events won't be triggered. 

```
    // Add a name change handler - notice that we add this to the instance not the Model itself
    me.on('change:name', function() {
        console.log(`Name changed to ${this.attributes.name}`); 
    });
    me.set({name: 'Kobe'});
    // If we set it manually through .attributes it won't call this function 
    me.attributes.name = 'Snoopy';
    me.set({name: 'Lebron'}, {silent: true});
    console.log(me.get('name')); 
```

A good place to add listeners in is in the `initialize` function. Note that changing more than one attribute at once only calls the function once. 

```
    // Add a listener in the initialize functions 
    var Person = Backbone.Model.extend({
        defaults: {
            name: '',
            species: 'Human'
        },
        initialize: function() {
            console.log(`New human ${this.attributes.name}!`);
            this.on('change', () => {console.log('attributes changed!');});
        }
    });
    var me = new Person({name: 'Dom'});
    me.set({name: 'Steph'});
```

### validation 
Backbone supports model validation through model.validate(), which allows checking the attribute values for a model prior to setting them. By default, validation occurs when the model is persisted using the save() method or when set() is called if {validate:true} is passed as an argument.  
We can also add attribute-specific listeners and define methods directly in the Model object - "setTitle" in this example. 

```
    // Add an attribute specific listener
    var Movie = Backbone.Model.extend({
        defaults: {
            title: '',
            length: 0
        },
        initialize: function() {
            console.log('Movie initialized');
            this.on('change:title', () => {console.log('Movie title updated!');});
        },
        validate: function(attributes) {
            if (attributes.title == '') {
                return('Remember to set a title for your movie');
            }
        },
        // we can also call .set methods in defined methods 
        setTitle: function(newTitle) {
            this.set('title', newTitle);
        }
    });
    var batman = new Movie({title: 'Batman Begins', 'length': '150'});
    batman.setTitle('The Dark Knight');
    batman.set('length', 165); // function was not called
    // Test validation 
    var newMovie = new Movie();
    newMovie.validate(newMovie.attributes);
```


## Views
Views in Backbone don’t contain the HTML markup for your application; they contain the logic behind the presentation of the model’s data to the user. This is usually achieved using JavaScript templating (e.g., Underscore Microtemplates, Mustache, jQuery-tmpl, etc.). A view’s render() method can be bound to a model’s change() event, enabling the view to instantly reflect model changes without requiring a full page refresh.


### el
el is basically a reference to a DOM element and all views must have one. Views can use el to compose their element’s content and then insert it into the DOM all at once, which makes for faster rendering because the browser performs the minimum required number of reflows and repaints. **There are two ways to associate a DOM element with a view: a new element can be created for the view and subsequently added to the DOM (el) or a reference can be made to an element which already exists in the page (referance an element by id for instance).**

#### Create a new element for your view 
If you want to create a new element for your view, set any combination of the following properties on the view: tagName, id, and className. A new element will be created for you by the library and a reference to it will be available at the el property. If nothing is specified  tagName defaults to div.  
This is why the `tagName` property doesn't work if I use a jQuery selector to select an element by `Id` - it won't overwrite an already existing element - we should instead create a new one.

```
    // Create a new element for the view 
    // Assigning className and Ids are optional 
    var TodoView = Backbone.View.extend({
        tagName: 'ul',
        className: 'container homepage myClass', // we can assign multiple classes
        id: 'toDos'
    });
    var TodosView = new TodoView();
    console.log(TodosView.el);
```

#### Set el to pre-existing DOM element
We can specify where to render a view by manually setting `el: #id` in the constructor.  If we this we can see that setting `el` to an element overrides the 'tagName', 'className', and 'id' attributes, and ignores these in favor of those present on the selected DOM element.

```
    // Set el to a pre-existing div (<div id='container'>Container</div>)
    var TodoView = Backbone.View.extend({
        tagName: 'ul',
        className: 'container homepage myClass', // we can assign multiple classes
        id: 'toDos',
        el: '#container'
    });
    var TodosView = new TodoView();
    console.log(TodosView.el); // we can see that setting el to an element overrides the 'tagName', 'className', and 'id' attributes.
```

### setElement
### .trigger()
If you need to apply an existing Backbone view to a different DOM element `setElement` can be used for this purpose. Overriding `this.el` needs to both change the DOM reference and re-bind events to the new element (and unbind from the old).
setElement will create a cached $el reference for you, moving the delegated events for a view from the old element to the new one.

`.trigger()` - mimics the event that you pass into it.


### render

## events and template 
The Backbone events hash allows us to attach event listeners to either el-relative custom selectors, or directly to el if no selector is provided. An event takes the form of a key-value pair 'eventName selector': 'callbackFunction' and a number of DOM event-types are supported, including click, submit, mouseover, dblclick and more.

First function example of a MV* framework.  The key points to highlight here are that the `.template` method in the view needs a template passed into it - selected here with jQuery.  Next the `events` listeners are only invoked for `DOM` events.  If we want to add listeners for Backbone / JS events we need to add then to specific instances using the initialize method.  The example here uses the `.listenTo` syntax, it calls handleChange after the backbone `.set` Model method triggers an `change` event on the underlying model.

```
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id='container'></div>
<style>
    .bkg-cyan {
        background: rgba(0, 255, 255, 0.7);
    }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="http://underscorejs.org/underscore-min.js"></script>
<script src="http://backbonejs.org/backbone-min.js"></script>
<script type="text/template" id="movie-template">
    Movies:
    <ul>
        <li>Title: <%= title %> </li>
        <li>Minutes: <%= minutes %></li>
    </ul>
</script>
<script>

    // Define Model 
    var MovieModel = Backbone.Model.extend({
        defaults: {
            title: '',
            minutes: 0
        }
    });
    var batman = new MovieModel({
        title: 'Batman Begins',
        minutes: 135
    });
    console.log(batman);
    
    // Define View
    var MovieView = Backbone.View.extend({
        el: '#container',
        
        events: {
            'click li': 'toggleColor',
            'click li': 'logClick'
        },
        
        template: _.template($('#movie-template').html()),  // select template here
        
        render: function() {
            this.$el.html(this.template(this.model.attributes));
        },
        
        initialize: function() {
            // Add Backbone event listener (for non-DOM events)
            this.stopListening(this.model); // for memory purposes
            this.listenTo(this.model, 'change', this.handleChange);
            this.render();
        },
        
        logClick: function(e) {
            console.log('clicked!');
            console.log(this); // entire view object 
            console.log(e.target); // <li> element
        },
        
        toggleColor: function(e) {
            e.target.classList.toggle('bkg-cyan');
        },
            
        handleChange: function(e) {
            // console.log(e); // full View Element
            console.log('handleChange running...');
            this.render();
        }
    });
    // create instance of view with batman model 
    var batmanView = new MovieView({
        model: batman
    });
    // Update model to see if .listenTo method was invoked 
    batman.set('title', 'The Dark Knight');
    
</script>
</body>
</html>
```

## Collections 
Collections are sets of Models and are created by extending Backbone.Collection. Normally, when creating a collection you’ll also want to define a property specifying the type of model that your collection will contain, along with any instance properties required. 
  
**Example Collection:**
```
    // Collections 
    var Clothing = Backbone.Model.extend({
        defaults: {
            type: '',
            quantity: 0
        }
    });
    var shirts = new Clothing({type: 't-shirt', quantity: 4});
    var pants = new Clothing({type: 'jeans', quantity: 2});
    
    // Define collection for Clothing Model
    var ClothingCollection = Backbone.Collection.extend({
        model: Clothing
    });
    
    // Pass an array of models to the Collection 
    var myClothing = new ClothingCollection([shirts, pants]);
    console.log(myClothing);
    // Access first model 
    console.log(myClothing.models[0]);
```

### add and remove 
The add and remove methods allow us to add / remove individual models or arrays of models from our Collection. 

```
    // Add and remove 
    var socks = new Clothing({type: 'nike-socks', quantity: 14});
    myClothing.add(socks);
    console.log(myClothing.models);
    // We can add / remove individual models and arrays 
    myClothing.remove([socks, pants]);
    console.log(myClothing.models);
```

### id, cid, idAttribute 
Each model in Backbone has an id, which is a unique identifier that is either an integer or string (e.g., a UUID). Models also have a cid (client id) which is automatically generated by Backbone when the model is created. Either identifier can be used to retrieve a model from a collection. The main difference between them is that the cid is generated by Backbone. The idAttribute is the identifying attribute name of the model returned from the server (i.e. the  id in your database) - it's automatically set to `id` but you can manually set it to the key from your DB, for instance `userId`. - this needs to be done in the model definition.

### Collection.get()
Collection.get() accepts a single id and retrieves the corresponding model.
```
    myClothing.get('c11'); // retrieve by cid
```


## Notes from Chris on BackBone

### REST / CRUD
Each REST command is centered around a resource. In REST, a resource is really anything that can be pointed to via HTTP protocol. For example, an image, a website, a document or a weather service. The possibilities are almost endless.

+ REST - Representational State Transfer - an architectural style designed for distributed hypermedia (or API)
+ API - Application Programming Interface: Another way to think of an API is to define it as a web service that conforms to the architectural principles of REST. Each API is called by issuing a standard HTTP request method: POST, GET, PUT and less commonly, DELETE.
  
CRUD was developed as standard database commands - not as way to create modern API.  Developers should be able to make the distinction between REST and the principles of other options like SOAP, COBRA and RMI.

If we run these in a browser we are performing `GET` calls: 
```
- knb.ecoinformatics.org/ (/ is the first folder or collection)
- knb.ecoinformatics.org/knb/d1/mn/v2 - API endpoint 
- get knbecoinformatics.org/knb/d1/mn/v2/object (this would give you a list of all the pids)
- post knbecoinformatics.org/knb/d1/mn/v2/object/{pid} + sysmeta etc. 
```

### ObjectFormats Collection 
File exists in src/js/collections.ObjectFormats.js

```
    var ObjectFormats = Backbone.Collection.extend({
        
        model: ObjectFormat,
        
        // this function tells ObjectFormats where to get its list of resources from.  It contains the endpoint:  `https://cn.dataone.org/cn/v1/formats` 
        url: function() {
            
            // no need for authentication token, just the URL
            return MetacatUI.appModel.get("formatsServiceUrl");
            
        },
        
        // We can use the `extend` method from underscore to modify the fetch function. We want to return it in text not the default format, json.  Then we fetch (CURL GET) to fetch the endpoint returned by the url() method.
        fetch: function(options) {
            var fetchOptions = _.extend({dataType: "text"}, options);
            
            return Backbone.Model.prototype.fetch.call(this, fetchOptions);
            
        },
        
        /* Parse the XML response from the CN */
        parse: function(response) {
            
            // If the collection is already parsed, just return it
            if ( typeof response === "object" ) return response;
            
            // Otherwise, parse it
            var x2js = new X2JS();
            var formats = x2js.xml_str2json(response);
            
            return formats.objectFormatList.objectFormat;
        }

    });
```

From the model attribute we see that this is a Collection of the Objectformat model in `src/models/formats/Objectformat.js`. Basic overview of the app logic can be found here: https://github.com/NCEAS/metacatui/blob/master/docs/design/editor/images/editor-design.png

### Entry point 
index.html is the entry point - We can see the `loading-app` icon there.  Afterwards it pulls in `src=metacatui/loader.js?v=2.5.1`.  