# Front End Libraries 
These are my notes from the Front End Libraries [certification](https://learn.freecodecamp.org/front-end-libraries/bootstrap) from FreeCodeCamp! 

## Bootstrap 
Bootstrap is a front-end framework used to design responsive web pages and web applications. It takes a mobile-first approach to web development. Bootstrap includes pre-built CSS styles and classes, plus some JavaScript functionality. Bootstrap uses a responsive 12 column grid layout and has design templates for: buttons, images, tables, forms, and navigation.
  
Bootstrap will figure out how wide your screen is and respond by resizing your HTML elements - hence the name Responsive Design. 

### Add bootstrap 
You can add bootstrap by adding this code snippet to the top of your HTML
```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>
```

### Bootstrap classes
class | explanation 
------------------------- | ---------------------------------------------------------
`class = img-responsive` |  make an image fit exactly the width of your screen.
`class = text-center` | center text 

### Buttons 
Bootstrap has default button styles that look better than normal ones.  
```
<button class="btn btn-default">Submit</button>
```
If we add the `btn-block` class it will expand to fill the horizontal space and any elements that follow it will be pushed to a new line. 
```
<button class="btn btn-default btn-block">Submit</button>
```
The `btn-primary` class is the main color you'll use in your app.  We use this in place of `btn-default`
The `btn-info` is another color scheme that calls attention to the user. (lighter blue)
The `btn-danger` class provides a red styling - warns of a destructive action like deleting.  

