# Monthly Selling Options Notes 

## Chapter 1 
Reccomends two strategies: 

+ Selling puts and calls using cash secured options and credit spreads
+ Selling covered calls

You can't have a stock option without a stock, but you can have a stock without an option.

A call option is the right to buy a stock or an ETF; a put option is the right to sell a stock or ETF. One call or put is comprised of 100 shares of a stock or an ETF - no exceptions.  The main strategy here is selling options - other strategies like naked calls, bull call spread, ratio spread, etc. are not as effective. Purchasing options carries more risk - time decay works against you and you only make money if the price hits your call or put number.  


## Chapter 3 
Benefits of selling options: 

+ you can make money whether the stock market goes up or down 
+ low, controllable risk 
+ high liquidity - buy or sell at any time 

ETF - An exchange-traded fund (ETF) is an investment fund traded on stock exchanges, much like stocks.[1][2] An ETF holds assets such as stocks, commodities, or bonds

Each option is attached to a stock or ETF and each stock or ETF has a symbol.  Example: General Electric has the symbol GE. Orders to buy and sell options are handled through online brokerages.  Options contracts trade on various US securities exchanges (New York Stock Exchange - NYSE, Pacific Stock Exchange - PSE, etc.)

## Chapter 4 
You should generally sell options that favor the market trend.  You don't have to predict where the market goes - but you do have to predict where it won't go (a much easier prospect). Your profit is limited to the premium you collect when you sell the option.  Option premiums are based on market volatility - higher volatility = higher premium. 

Commissions - deducted from your premium at the time of the trade.  A typical commission is 7.95 + .75 cents per option. 

### Weekly Calls and Puts 
Incur higher brokerage fees and commissions since you're making more trades.  You also have to put the strike price closer to the actual stock price since you're working with a short time frame.  The advantage is there's less time for the stock price to go against you, you can get a higher ROI given the short time period, and you can turn your money over faster.  

### Longer than a week 
You can make a higher premium per trade, requires less time to manage your trades and you don't incur as many commission fees. 


## Chapter 5 
Try to sell a bid at the midpoint of the bid and the ask price.  There are several major factors affecting the premium price of an option, including a change in the price of the underlying stock, the strike price, the amount of time left until expiration of the option, and the volatility of the stock or ETF. The closer the strike price is to the actual value of the stock the higher the premium and vice versa.  

We recommend selecting premiums that are equivalent to a Delta no higher than 12. A Delta of 12 percent is far below the market price of the security. If you were selling a call, a Delta 12 would be far above the market price of the security. This Delta gives you an 88 percent chance that you will have a successful trade.

**Volume**: Daily activity of an option - describes how many contracts changed hands on any given option during the day.  You want to see at least 100,000 because that implies the contract is liquid.
**Open interest:** The number of outstanding contracts that haven't been closed out or exercised.  Better indicator of liquidity than volume. Open orders are listed for each option strike price. 
**Implied Volatility** - higher volatility generally favors the trader.  

## Vocabulary 

+ Assignment - When you get assigned you're required to purchase the shares at the strike price.  
+ ATM (at the money) - An option with a strike price that's equal to the price of the security. 
+ Bear Call Spread - 
+ Bull Put Spread 
+ Covered call - when an investor owns at least 100 shares of a contract then you can sell a "covered" call against the security and receive a premium. 
+ Early exercise - when an owner buys back an option prior to its expiration date 
+ ITM (In the money option) - When the price is above strike on a call option and vice versa for puts. 
+ Iron Condor - 
+ LEAPS - one to five year options 
+ Limit Order vs. Market Order - buy or sell securities at a certain price vs a market order where you buy them immediately.  They recommend using limit orders. 
+ Naked - Put or call options that are uncovered.  Unlimited loss potential. Only use cash-secured orders. 
+ Open interest - the total open options contracts not repurchased or exercised. 
+ OptionChain - a list of all the strike bid and ask pries for an option 
+ OTM (Out of the money) - an option with a strike price that's away from the actual security price
+ P/E - price to earnings ratio.  Price of security / its earnings per share. 
+ Rollover - moving a position from one expiration period to another - for another premium.  
+ Time decay - theta 


## Questions 
1. Investors should only sell options on securities that they are willing to own at the strike price at which they sold the option.  
2. Credit spreads eliminate unlimited risk? 
3. If a commission is 7.95 + .75 cents per option what's the most cost effective way to sell options?  Probably in batches? 
4. We recommend selecting premiums that are equivalent to a Delta no higher than 12. A Delta of 12 percent is far below the market price of the security. If you were selling a call, a Delta 12 would be far above the market price of the security. This Delta gives you an 88 percent chance that you will have a successful trade. -- need an example of this. 
5. We recommend longer expiration periods, up to eight weeks. We want you to select stable securities that pass our screening criteria and pay favorable premiums. -- Why is this the case / why does Harrison trade weekly?
6. Is volume important? They recommend looking for at least 100,000.  Also open interest.  
7. Bear Call spread? 
8. Bid and Ask 
9. Naked call/put example?  





